OLD/config/routes.rb
Rails.application.routes.draw do
  resources :references_snaks2s

  resources :references_snaks

  resources :references

  resources :qualifiers

  resources :sitelinks

  resources :claims

  resources :descriptions

  resources :labels

  resources :aliases

  resources :entities

  resources :tests


  post 'home/addEntity' => 'home#addEntity'


  #Ruta para descargar pdfs
  resources :usuarios do
    member do
      get :download
    end
  end


  root 'home#index'

  #Ruta pa Twilio
  #post 'twilio/voice' => 'twilio#voice'


  #sesiones
  resource :session, only: [:new, :create, :destroy]


  match 'destroy_them_all', to: 'home#destroy_them_all', via: :delete


end

OLD/app/models/alias.rb
class Alias < ActiveRecord::Base
end

OLD/app/models/claim.rb
class Claim < ActiveRecord::Base
end

OLD/app/models/description.rb
class Description < ActiveRecord::Base
end

OLD/app/models/entity.rb
class Entity < ActiveRecord::Base
end

OLD/app/models/label.rb
class Label < ActiveRecord::Base
end

OLD/app/models/qualifier.rb
class Qualifier < ActiveRecord::Base
end

OLD/app/models/reference.rb
class Reference < ActiveRecord::Base
end

OLD/app/models/references_snak.rb
class ReferencesSnak < ActiveRecord::Base
end

OLD/app/models/references_snaks2.rb
class ReferencesSnaks2 < ActiveRecord::Base
end

OLD/app/models/sitelink.rb
class Sitelink < ActiveRecord::Base
end

OLD/app/models/test.rb
class Test < ActiveRecord::Base
end

OLD/app/controllers/references_snaks_controller.rb
class ReferencesSnaksController < ApplicationController
  before_action :set_references_snak, only: [:show, :edit, :update, :destroy]

  # GET /references_snaks
  # GET /references_snaks.json
  def index
    @references_snaks = ReferencesSnak.all
  end

  # GET /references_snaks/1
  # GET /references_snaks/1.json
  def show
  end

  # GET /references_snaks/new
  def new
    @references_snak = ReferencesSnak.new
  end

  # GET /references_snaks/1/edit
  def edit
  end

  # POST /references_snaks
  # POST /references_snaks.json
  def create
    @references_snak = ReferencesSnak.new(references_snak_params)

    respond_to do |format|
      if @references_snak.save
        format.html { redirect_to @references_snak, notice: 'References snak was successfully created.' }
        format.json { render :show, status: :created, location: @references_snak }
      else
        format.html { render :new }
        format.json { render json: @references_snak.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references_snaks/1
  # PATCH/PUT /references_snaks/1.json
  def update
    respond_to do |format|
      if @references_snak.update(references_snak_params)
        format.html { redirect_to @references_snak, notice: 'References snak was successfully updated.' }
        format.json { render :show, status: :ok, location: @references_snak }
      else
        format.html { render :edit }
        format.json { render json: @references_snak.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references_snaks/1
  # DELETE /references_snaks/1.json
  def destroy
    @references_snak.destroy
    respond_to do |format|
      format.html { redirect_to references_snaks_url, notice: 'References snak was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_references_snak
      @references_snak = ReferencesSnak.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def references_snak_params
      params.require(:references_snak).permit(:snak, :snaktype, :property, :datatype)
    end
end

OLD/app/helpers/aliases_helper.rb
module AliasesHelper
end

OLD/app/helpers/claims_helper.rb
module ClaimsHelper
end

OLD/app/helpers/entities_helper.rb
module EntitiesHelper
end

OLD/app/helpers/home_helper.rb
module HomeHelper
end

OLD/app/helpers/labels_helper.rb
module LabelsHelper
end

OLD/app/helpers/qualifiers_helper.rb
module QualifiersHelper
end

OLD/app/helpers/references_snaks_helper.rb
module ReferencesSnaksHelper
end

OLD/app/helpers/sessions_helper.rb
module SessionsHelper
end

OLD/app/helpers/sitelinks_helper.rb
module SitelinksHelper
end

OLD/app/helpers/tests_helper.rb
module TestsHelper
end

OLD/app/helpers/twilio_helper.rb
module TwilioHelper
end

OLD/app/views/references_snaks/_form.html.erb
<%= form_for(@references_snak) do |f| %>
  <% if @references_snak.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@references_snak.errors.count, "error") %> prohibited this references_snak from being saved:</h2>

      <ul>
      <% @references_snak.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snak %><br>
    <%= f.text_field :snak %>
  </div>
  <div class="field">
    <%= f.label :snaktype %><br>
    <%= f.text_field :snaktype %>
  </div>
  <div class="field">
    <%= f.label :property %><br>
    <%= f.text_field :property %>
  </div>
  <div class="field">
    <%= f.label :datatype %><br>
    <%= f.text_field :datatype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/app/views/references_snaks/edit.html.erb
<h1>Editing References Snak</h1>

<%= render 'form' %>

<%= link_to 'Show', @references_snak %> |
<%= link_to 'Back', references_snaks_path %>

OLD/app/views/references_snaks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing References Snaks</h1>

<table>
  <thead>
    <tr>
      <th>Snak</th>
      <th>Snaktype</th>
      <th>Property</th>
      <th>Datatype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references_snaks.each do |references_snak| %>
      <tr>
        <td><%= references_snak.snak %></td>
        <td><%= references_snak.snaktype %></td>
        <td><%= references_snak.property %></td>
        <td><%= references_snak.datatype %></td>
        <td><%= link_to 'Show', references_snak %></td>
        <td><%= link_to 'Edit', edit_references_snak_path(references_snak) %></td>
        <td><%= link_to 'Destroy', references_snak, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New References snak', new_references_snak_path %>

OLD/app/views/references_snaks/new.html.erb
<h1>New References Snak</h1>

<%= render 'form' %>

<%= link_to 'Back', references_snaks_path %>

OLD/app/views/references_snaks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Snak:</strong>
  <%= @references_snak.snak %>
</p>

<p>
  <strong>Snaktype:</strong>
  <%= @references_snak.snaktype %>
</p>

<p>
  <strong>Property:</strong>
  <%= @references_snak.property %>
</p>

<p>
  <strong>Datatype:</strong>
  <%= @references_snak.datatype %>
</p>

<%= link_to 'Edit', edit_references_snak_path(@references_snak) %> |
<%= link_to 'Back', references_snaks_path %>