OLD/config/routes.rb
Rails.application.routes.draw do
  resources :references_snaks2s

  resources :references_snaks

  resources :references

  resources :qualifiers

  resources :sitelinks

  resources :claims

  resources :descriptions

  resources :labels

  resources :aliases

  resources :entities

  resources :tests


  post 'home/addEntity' => 'home#addEntity'


  #Ruta para descargar pdfs
  resources :usuarios do
    member do
      get :download
    end
  end


  root 'home#index'

  #Ruta pa Twilio
  #post 'twilio/voice' => 'twilio#voice'


  #sesiones
  resource :session, only: [:new, :create, :destroy]


  match 'destroy_them_all', to: 'home#destroy_them_all', via: :delete


end

OLD/app/models/alias.rb
class Alias < ActiveRecord::Base
end

OLD/app/models/claim.rb
class Claim < ActiveRecord::Base
end

OLD/app/models/description.rb
class Description < ActiveRecord::Base
end

OLD/app/models/entity.rb
class Entity < ActiveRecord::Base
end

OLD/app/models/label.rb
class Label < ActiveRecord::Base
end

OLD/app/models/qualifier.rb
class Qualifier < ActiveRecord::Base
end

OLD/app/models/reference.rb
class Reference < ActiveRecord::Base
end

OLD/app/models/references_snak.rb
class ReferencesSnak < ActiveRecord::Base
end

OLD/app/models/references_snaks2.rb
class ReferencesSnaks2 < ActiveRecord::Base
end

OLD/app/models/sitelink.rb
class Sitelink < ActiveRecord::Base
end

OLD/app/models/test.rb
class Test < ActiveRecord::Base
end

OLD/app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  before_action :set_alias, only: [:show, :edit, :update, :destroy]

  # GET /aliases
  # GET /aliases.json
  def index
    @aliases = Alias.all
  end

  # GET /aliases/1
  # GET /aliases/1.json
  def show
  end

  # GET /aliases/new
  def new
    @alias = Alias.new
  end

  # GET /aliases/1/edit
  def edit
  end

  # POST /aliases
  # POST /aliases.json
  def create
    @alias = Alias.new(alias_params)

    respond_to do |format|
      if @alias.save
        format.html { redirect_to @alias, notice: 'Alias was successfully created.' }
        format.json { render :show, status: :created, location: @alias }
      else
        format.html { render :new }
        format.json { render json: @alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliases/1
  # PATCH/PUT /aliases/1.json
  def update
    respond_to do |format|
      if @alias.update(alias_params)
        format.html { redirect_to @alias, notice: 'Alias was successfully updated.' }
        format.json { render :show, status: :ok, location: @alias }
      else
        format.html { render :edit }
        format.json { render json: @alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliases/1
  # DELETE /aliases/1.json
  def destroy
    @alias.destroy
    respond_to do |format|
      format.html { redirect_to aliases_url, notice: 'Alias was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alias
      @alias = Alias.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alias_params
      params.require(:alias).permit(:aid, :language, :value)
    end
end

OLD/app/helpers/aliases_helper.rb
module AliasesHelper
end

OLD/app/helpers/claims_helper.rb
module ClaimsHelper
end

OLD/app/helpers/entities_helper.rb
module EntitiesHelper
end

OLD/app/helpers/home_helper.rb
module HomeHelper
end

OLD/app/helpers/labels_helper.rb
module LabelsHelper
end

OLD/app/helpers/qualifiers_helper.rb
module QualifiersHelper
end

OLD/app/helpers/sessions_helper.rb
module SessionsHelper
end

OLD/app/helpers/sitelinks_helper.rb
module SitelinksHelper
end

OLD/app/helpers/tests_helper.rb
module TestsHelper
end

OLD/app/helpers/twilio_helper.rb
module TwilioHelper
end

OLD/app/views/aliases/_form.html.erb
<%= form_for(@alias) do |f| %>
  <% if @alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alias.errors.count, "error") %> prohibited this alias from being saved:</h2>

      <ul>
      <% @alias.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aid %><br>
    <%= f.text_field :aid %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/app/views/aliases/edit.html.erb
<h1>Editing Alias</h1>

<%= render 'form' %>

<%= link_to 'Show', @alias %> |
<%= link_to 'Back', aliases_path %>

OLD/app/views/aliases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aliases</h1>

<table>
  <thead>
    <tr>
      <th>Aid</th>
      <th>Language</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aliases.each do |aliasd| %>
      <tr>
        <td><%= aliasd.aid %></td>
        <td><%= aliasd.language %></td>
        <td><%= aliasd.value %></td>
        <td><%= link_to 'Show', aliasd %></td>
        <td><%= link_to 'Edit', edit_alias_path(alias) %></td>
        <td><%= link_to 'Destroy', aliasd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alias', new_alias_path %>

OLD/app/views/aliases/new.html.erb
<h1>New Alias</h1>

<%= render 'form' %>

<%= link_to 'Back', aliases_path %>

OLD/app/views/aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aid:</strong>
  <%= @alias.aid %>
</p>

<p>
  <strong>Language:</strong>
  <%= @alias.language %>
</p>

<p>
  <strong>Value:</strong>
  <%= @alias.value %>
</p>

<%= link_to 'Edit', edit_alias_path(@alias) %> |
<%= link_to 'Back', aliases_path %>