OLD/config/routes.rb
Rails.application.routes.draw do
  resources :references_snaks2s

  resources :references_snaks

  resources :references

  resources :qualifiers

  resources :sitelinks

  resources :claims

  resources :descriptions

  resources :labels

  resources :aliases

  resources :entities

  resources :tests


  post 'home/addEntity' => 'home#addEntity'


  #Ruta para descargar pdfs
  resources :usuarios do
    member do
      get :download
    end
  end


  root 'home#index'

  #Ruta pa Twilio
  #post 'twilio/voice' => 'twilio#voice'


  #sesiones
  resource :session, only: [:new, :create, :destroy]


  match 'destroy_them_all', to: 'home#destroy_them_all', via: :delete


end

OLD/app/models/alias.rb
class Alias < ActiveRecord::Base
end

OLD/app/models/claim.rb
class Claim < ActiveRecord::Base
end

OLD/app/models/description.rb
class Description < ActiveRecord::Base
end

OLD/app/models/entity.rb
class Entity < ActiveRecord::Base
end

OLD/app/models/label.rb
class Label < ActiveRecord::Base
end

OLD/app/models/qualifier.rb
class Qualifier < ActiveRecord::Base
end

OLD/app/models/reference.rb
class Reference < ActiveRecord::Base
end

OLD/app/models/references_snak.rb
class ReferencesSnak < ActiveRecord::Base
end

OLD/app/models/references_snaks2.rb
class ReferencesSnaks2 < ActiveRecord::Base
end

OLD/app/models/sitelink.rb
class Sitelink < ActiveRecord::Base
end

OLD/app/models/test.rb
class Test < ActiveRecord::Base
end

OLD/app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:snak, :hash)
    end
end

OLD/app/helpers/aliases_helper.rb
module AliasesHelper
end

OLD/app/helpers/claims_helper.rb
module ClaimsHelper
end

OLD/app/helpers/entities_helper.rb
module EntitiesHelper
end

OLD/app/helpers/home_helper.rb
module HomeHelper
end

OLD/app/helpers/labels_helper.rb
module LabelsHelper
end

OLD/app/helpers/qualifiers_helper.rb
module QualifiersHelper
end

OLD/app/helpers/references_helper.rb
module ReferencesHelper
end

OLD/app/helpers/sessions_helper.rb
module SessionsHelper
end

OLD/app/helpers/sitelinks_helper.rb
module SitelinksHelper
end

OLD/app/helpers/tests_helper.rb
module TestsHelper
end

OLD/app/helpers/twilio_helper.rb
module TwilioHelper
end

OLD/app/views/references/_form.html.erb
<%= form_for(@reference) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snak %><br>
    <%= f.text_field :snak %>
  </div>
  <div class="field">
    <%= f.label :hash %><br>
    <%= f.text_field :hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

OLD/app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing References</h1>

<table>
  <thead>
    <tr>
      <th>Snak</th>
      <th>Hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.snak %></td>
        <td><%= reference.hash %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

OLD/app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

OLD/app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Snak:</strong>
  <%= @reference.snak %>
</p>

<p>
  <strong>Hash:</strong>
  <%= @reference.hash %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>