OLD/config/routes.rb
Rails.application.routes.draw do
  resources :references_snaks2s

  resources :references_snaks

  resources :references

  resources :qualifiers

  resources :sitelinks

  resources :claims

  resources :descriptions

  resources :labels

  resources :aliases

  resources :entities

  resources :tests


  post 'home/addEntity' => 'home#addEntity'


  #Ruta para descargar pdfs
  resources :usuarios do
    member do
      get :download
    end
  end


  root 'home#index'

  #Ruta pa Twilio
  #post 'twilio/voice' => 'twilio#voice'


  #sesiones
  resource :session, only: [:new, :create, :destroy]


  match 'destroy_them_all', to: 'home#destroy_them_all', via: :delete


end

OLD/app/models/alias.rb
class Alias < ActiveRecord::Base
end

OLD/app/models/claim.rb
class Claim < ActiveRecord::Base
end

OLD/app/models/description.rb
class Description < ActiveRecord::Base
end

OLD/app/models/entity.rb
class Entity < ActiveRecord::Base
end

OLD/app/models/label.rb
class Label < ActiveRecord::Base
end

OLD/app/models/qualifier.rb
class Qualifier < ActiveRecord::Base
end

OLD/app/models/reference.rb
class Reference < ActiveRecord::Base
end

OLD/app/models/references_snak.rb
class ReferencesSnak < ActiveRecord::Base
end

OLD/app/models/references_snaks2.rb
class ReferencesSnaks2 < ActiveRecord::Base
end

OLD/app/models/sitelink.rb
class Sitelink < ActiveRecord::Base
end

OLD/app/models/test.rb
class Test < ActiveRecord::Base
end

OLD/app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:pageid, :ns, :title, :lastrevid, :modified, :eid, :type, :property_datatype)
    end
end

OLD/app/helpers/aliases_helper.rb
module AliasesHelper
end

OLD/app/helpers/claims_helper.rb
module ClaimsHelper
end

OLD/app/helpers/entities_helper.rb
module EntitiesHelper
end

OLD/app/helpers/home_helper.rb
module HomeHelper
end

OLD/app/helpers/labels_helper.rb
module LabelsHelper
end

OLD/app/helpers/qualifiers_helper.rb
module QualifiersHelper
end

OLD/app/helpers/references_helper.rb
module ReferencesHelper
end

OLD/app/helpers/sessions_helper.rb
module SessionsHelper
end

OLD/app/helpers/sitelinks_helper.rb
module SitelinksHelper
end

OLD/app/helpers/tests_helper.rb
module TestsHelper
end

OLD/app/helpers/twilio_helper.rb
module TwilioHelper
end

OLD/app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pageid %><br>
    <%= f.text_field :pageid %>
  </div>
  <div class="field">
    <%= f.label :ns %><br>
    <%= f.text_field :ns %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :lastrevid %><br>
    <%= f.text_field :lastrevid %>
  </div>
  <div class="field">
    <%= f.label :modified %><br>
    <%= f.text_field :modified %>
  </div>
  <div class="field">
    <%= f.label :eid %><br>
    <%= f.text_field :eid %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :property_datatype %><br>
    <%= f.text_field :property_datatype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OLD/app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

OLD/app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entities</h1>

<table>
  <thead>
    <tr>
      <th>Pageid</th>
      <th>Ns</th>
      <th>Title</th>
      <th>Lastrevid</th>
      <th>Modified</th>
      <th>Eid</th>
      <th>Type</th>
      <th>Property datatype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.pageid %></td>
        <td><%= entity.ns %></td>
        <td><%= entity.title %></td>
        <td><%= entity.lastrevid %></td>
        <td><%= entity.modified %></td>
        <td><%= entity.eid %></td>
        <td><%= entity.type_e %></td>
        <td><%= entity.property_datatype %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

OLD/app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

OLD/app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pageid:</strong>
  <%= @entity.pageid %>
</p>

<p>
  <strong>Ns:</strong>
  <%= @entity.ns %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entity.title %>
</p>

<p>
  <strong>Lastrevid:</strong>
  <%= @entity.lastrevid %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @entity.modified %>
</p>

<p>
  <strong>Eid:</strong>
  <%= @entity.eid %>
</p>

<p>
  <strong>Type:</strong>
  <%= @entity.type %>
</p>

<p>
  <strong>Property datatype:</strong>
  <%= @entity.property_datatype %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>